# https://ci.appveyor.com/project/goanpeca/loghub

matrix:
  fast_finish: true

branches:
  only:
    - master 

environment:
  global:
    # Used by qthelpers to close widgets after a defined time
    TEST_CI: True
    # Environment variables used by astropy helpers
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                      # of 32 bit and 64 bit builds are needed, move this
                      # to the matrix section.

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.5"
    - PYTHON_VERSION: "3.6"

platform:
  -x64

install:
  # Astropy ci-helpers. See https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "conda install -q jinja2 coveralls mock pytest pytest-cov"
  - "python setup.py develop"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - pytest -x -vv --cov=loghub --cov-report=term-missing loghub
