codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "18...100"  
  status:
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
   
comment: false

ignore:
  - "loghub/external/github.py"
  - "loghub/external/__init__.py"
