version: 2

main: &main
    machine: true
    steps:
      - checkout
      - run:
          command: docker pull continuumio/miniconda3:latest
      - run:
          command: ./.circleci/install.sh
      - run:
          command: ./.circleci/run_tests.sh
      - run:
          command: ./.circleci/coverage.sh

jobs:
  python2.7:
    <<: *main
    environment:
      - PYTHON_VERSION: "2.7"

  python3.5:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.5"

  python3.6:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.6"

workflows:
  version: 2
  build_and_test:
    jobs:
      - python2.7
      - python3.5
      - python3.6
